### ISSUE TITLE
Request.

### ISSUE THREAD

**Issue by Firehouse-Games** [Saibot393/enhancedcombathud-yzecoriolis#3]
I was wondering if it would be to much of a hassle to have argon combat indicating what is an Slow action, Fast action and free action.
The following is an example:
![image](https://github.com/Saibot393/enhancedcombathud-yzecoriolis/assets/108539457/9d4a27e3-5b71-44c9-af69-205f33d1aa3d)

**Comment by Saibot393** [comment]
I decided on the current action setup where only the color marks the action type mainly due to three "problems":
1. There is only really one "default" normal action, reload, making this category awkwardly empty
2. Since all the actions points are in one pool i am not certain where to put the indicator, probably in the first "slow action" category or the "fast action" category?
3. The free actions fell like they are too reactionary or rather not really optional enough as to appear in the action bar

That being said, adding an alternative mode where the actions are sorted similar to the T2K argon HUD as shown above shouldn't really be much of a problem.

**Comment by Firehouse-Games** [comment]
The year zero engine is pretty much the same across the board.
Hope this page can help you with what I was suggesting.
By the way, thank you so much for your hard work, I really appreciate it.

**Comment by Firehouse-Games** [comment]
My apologies, I forgot to attach the screenshot.
![Screenshot_20240104_225410](https://github.com/Saibot393/enhancedcombathud-yzecoriolis/assets/108539457/7202e49b-9b0e-4f3b-9eb3-cf6eed22f19c)

**Comment by Saibot393** [comment]
I have added the client setting "Split action bar" with v1.4.0. I will leave this issue open for now in case i missed something with the split bar version.

**Comment by Firehouse-Games** [comment]
Thank you so much! Once again, I really appreciate it, and so everyone in
the community!
