### ISSUE TITLE
Coriolis 3AP Action Tracking

### ISSUE THREAD

**Issue by RicoMittelholzer** [Saibot393/enhancedcombathud-yzecoriolis#9]
Hi. thx so much for this cool Modul. Just two questions? In your description it says the module will track the 3AP's. But i did not found a way to use/spend or show the action tokens that are used. I guess you mean the coriolis action (1 AP, 2AP 3AP) z.b. when you fight. And is it possible to roll a weapon out of the interface? Sometimes it shows me if i want to shoot normal or fast, but cant roll. thx so much for your help. All best Rico

**Comment by Saibot393** [comment]
When a token is in combat small blue pips will appear between the buttons and the titles of the action categories. These pips will turn grey when they are used (internally the three action points are tracked, the slow action pip is blue if you have three points, the normal action pip is blue if you have at least two points, and the fast action pip has as many blue pips as you have action points).
Example:
![image](https://github.com/Saibot393/enhancedcombathud-yzecoriolis/assets/137942782/cc7bcd41-3906-4330-b740-1ee4d7e423fb)
There was a small bug that prevented some rolls from going through, that should now be fixed with the new v1.5.2. Once you have placed a weapon into a weapon slot above the portrait, you can select it, causing the left most buttons of the slow and normal actions sections to display this weapon. From there you can either click the button for a normal attack or hover over it to cause the options for aimed and quick attacks to show up
![image](https://github.com/Saibot393/enhancedcombathud-yzecoriolis/assets/137942782/0dbc6b15-3259-481a-9cba-6cb51ba25733)

**Comment by RicoMittelholzer** [comment]
Hi. I got it with the Action Tracking. That works, i just missed the little blue pips. Rolling a weapon dont work for me. I deactivated most of the modules, added new weapons to the slot, so i also see the normal and fast lets say shots. but the modul dont allow me to roll. Am i missing something? Also did not found any wrong adjustments in the settings. All Best Rico

**Comment by Saibot393** [comment]
Which version of the module are you using? Are there any errors in the console (F12) when trying to roll a weapon?

**Comment by RicoMittelholzer** [comment]
I use Version 1.5.2. No error in connection with argon.

**Comment by RicoMittelholzer** [comment]
ok wait. Just deactivate all modules, and now it works

**Comment by Saibot393** [comment]
Could you send me the .json export of the actor you tested it with so i can take a closer look?

**Comment by Saibot393** [comment]
Have you tried running [Find the culprit!](https://foundryvtt.com/packages/find-the-culprit/) to narrow which module might prevent the rolls from showing up?

**Comment by RicoMittelholzer** [comment]
I disabled all modules and one by one added them again. Now all works fine. Thats kind of strange, cause now as Argon works it still works with all other modules active. But hey thanks anyway.. Today is the first Session with your amazing module. I will let you know what the group says about. Best Rico

**Comment by Saibot393** [comment]
Yeah, sometimes foundry has a few strange hiccups.
I hope everything works well in your session, excited to hear what the opinions regarding the module are.
